### PR TITLE
chore: update deps and better handling for NodeJS version

### PR DESCRIPTION
**Pull request by aripalo**
<ul>
<li>Configure NodeJS min/max versions (min set to <code>18</code>, will be increased in v2)</li>
<li><details>

<summary>Run <code>pj upgrade</code>.</summary>

Before:
```sh
❯ npm outdated
Package                             Current    Wanted   Latest  Location                                        Depended by
@types/jest                          27.5.2    27.5.2  29.5.14  node_modules/@types/jest                        project
@types/node                        18.19.59  18.19.64   22.9.0  node_modules/@types/node                        project
@typescript-eslint/eslint-plugin     7.18.0    7.18.0   8.15.0  node_modules/@typescript-eslint/eslint-plugin   project
@typescript-eslint/parser            7.18.0    7.18.0   8.15.0  node_modules/@typescript-eslint/parser          project
aws-cdk-lib                         2.133.0   2.133.0  2.167.1  node_modules/aws-cdk-lib                        project
change-case                           4.1.2     4.1.2    5.4.4  node_modules/change-case                        project
constructs                           10.3.0    10.3.0   10.4.2  node_modules/constructs                         project
eslint                               8.57.1    8.57.1   9.15.0  node_modules/eslint                             project
eslint-import-resolver-typescript     2.7.1     2.7.1    3.6.3  node_modules/eslint-import-resolver-typescript  project
jest                                 27.5.1    27.5.1   29.7.0  node_modules/jest                               project
jest-junit                           15.0.0    15.0.0   16.0.0  node_modules/jest-junit                         project
jsii                                 5.3.55    5.3.59    5.6.0  node_modules/jsii                               project
jsii-diff                           1.104.0   1.105.0  1.105.0  node_modules/jsii-diff                          project
jsii-docgen                          10.5.5    10.5.7   10.5.7  node_modules/jsii-docgen                        project
jsii-pacmak                         1.104.0   1.105.0  1.105.0  node_modules/jsii-pacmak                        project
jsii-rosetta                         5.3.54    5.3.58    5.6.0  node_modules/jsii-rosetta                       project
projen                               0.88.6    0.88.9   0.90.3  node_modules/projen                             project
ts-jest                              27.1.5    27.1.5   29.2.5  node_modules/ts-jest                            project
typescript                            4.9.5     4.9.5    5.6.3  node_modules/typescript                         project
```

After:
```sh
❯ npm outdated
Package                             Current    Wanted   Latest  Location                                        Depended by
@types/jest                          27.5.2    27.5.2  29.5.14  node_modules/@types/jest                        project
@types/node                        18.19.64  18.19.64   22.9.0  node_modules/@types/node                        project
aws-cdk-lib                         2.133.0   2.133.0  2.167.1  node_modules/aws-cdk-lib                        project
change-case                           4.1.2     4.1.2    5.4.4  node_modules/change-case                        project
constructs                           10.3.0    10.3.0   10.4.2  node_modules/constructs                         project
eslint-import-resolver-typescript     2.7.1     2.7.1    3.6.3  node_modules/eslint-import-resolver-typescript  project
jest                                 27.5.1    27.5.1   29.7.0  node_modules/jest                               project
jest-junit                           15.0.0    15.0.0   16.0.0  node_modules/jest-junit                         project
jsii                                 5.3.59    5.3.59    5.6.0  node_modules/jsii                               project
jsii-rosetta                         5.3.58    5.3.58    5.6.0  node_modules/jsii-rosetta                       project
ts-jest                              27.1.5    27.1.5   29.2.5  node_modules/ts-jest                            project
typescript                            4.9.5     4.9.5    5.6.3  node_modules/typescript                         project
```

</details></li></ul>

### CODE REVIEW

**Review by jyrheikk — COMMENTED** [review]
suggestion: Could the Node version be updated?

**Review by jyrheikk — APPROVED** [review]
suggestion: Should

- `@types/node` (to match Node `20` instead of `18`) and
- `aws-cdk-lib` (`2.133` is a year old)

be updated, too.

**Comment by aripalo** [comment]
@jyrheikk:

> suggestion: Should
> 
>     * `@types/node` (to match Node `20` instead of `18`) and
> 
>     * `aws-cdk-lib` (`2.133` is a year old)
> 
> 
> be updated, too.

First one is a good point. I'll update that. It should match the node version used.

The second one isn't a problem. The idea is to define a "lowest common" `aws-cdk-lib` dependency, so if for some reason there are projects that use this running in old CDK version, we won't break them. That being said as we are doing a new version we could… but I might leave that for next major `v2` as I want the transition from `v0` to `v1` be as easy as possible.

**Comment by aripalo** [comment]
Based on the other comments, I decided to add better NodeJS version management: https://github.com/alma-cdk/project/pull/34/files#diff-bda22a3de7550efc76dd29e2a427a8d5abd5863f6e96a339ff47390d9bed7d14 

I defaulted to bit older v18, in case some users still running on old Node. Using the min version also verifies in the CI pipeline that it works with that.

**Review by jyrheikk — APPROVED** [review]

**Review by Hyperinen — APPROVED** [review]
LGTM

**Pull request merged**
